// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiMiUOzbHFeb3d1JyjrRjcZNfJvzXEVCU',
    appId: '1:39995634067:web:233012d5b83df2c18bb866',
    messagingSenderId: '39995634067',
    projectId: 'ecommerce-app-25698',
    authDomain: 'ecommerce-app-25698.firebaseapp.com',
    storageBucket: 'ecommerce-app-25698.appspot.com',
    measurementId: 'G-RBEW67T24E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnHTxo1Q0hqtq8rPpbHkoFj6zhrm5NoTs',
    appId: '1:39995634067:android:6961a4a52bd5c8508bb866',
    messagingSenderId: '39995634067',
    projectId: 'ecommerce-app-25698',
    storageBucket: 'ecommerce-app-25698.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-7m-8meokohtzE25T0eS-_2PrF8PvrRc',
    appId: '1:39995634067:ios:79a48735349642f58bb866',
    messagingSenderId: '39995634067',
    projectId: 'ecommerce-app-25698',
    storageBucket: 'ecommerce-app-25698.appspot.com',
    iosClientId: '39995634067-k1d9e8k1gh6lk8j1u4quibmmooj47j1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-7m-8meokohtzE25T0eS-_2PrF8PvrRc',
    appId: '1:39995634067:ios:5c4be29751771af48bb866',
    messagingSenderId: '39995634067',
    projectId: 'ecommerce-app-25698',
    storageBucket: 'ecommerce-app-25698.appspot.com',
    iosClientId: '39995634067-0af41894iki7np4fo6ka9b7afjn72u66.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
